### ISSUE TITLE
Could not use "DrupalTestsListenersHtmlOutputPrinter" as printer: class does not exist

### ISSUE THREAD

**Issue by brentgees** [finnef/lando-drupal8-test-debugging#5]
When trying to execute the first test from https://github.com/finnef/lando-drupal8-test-debugging#run, I get the following error:

`Could not use "DrupalTestsListenersHtmlOutputPrinter" as printer: class does not exist`

This did not allow me to execute any tests, I was able to fix this on my local machine by removing '--printer=\\Drupal\\Tests\\Listeners\\HtmlOutputPrinter' in the .lando.yml file.

I don't know if this is the best solution, but it helped me to execute all the tests without errors.

**Comment by finnef** [comment]
This was an config error where the slashes removed in the path \Drupal\Tests\Listeners\HtmlOutputPrinter
This was fixed in the 1.2 release
